#!/usr/bin/env python3
"""Generate ~/.codex/AGENTS.md from Claude Code agents and rules.

Reads agent definitions (.claude/agents/*.md) and rule files
(~/Task-Management/rules/*.md), then produces a single AGENTS.md for Codex CLI.

Usage:
    uv run python .scripts/generate-codex-agents-md.py \
        --agents-dir ~/.claude/agents \
        --rules-dir ~/.claude/rules \
        --output ~/.codex/AGENTS.md
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


def parse_frontmatter(text: str) -> tuple[dict[str, str], str]:
    """Extract YAML frontmatter and body from markdown."""
    if not text.startswith("---"):
        return {}, text
    end = text.find("---", 3)
    if end == -1:
        return {}, text
    fm_text = text[3:end].strip()
    body = text[end + 3 :].strip()
    meta: dict[str, str] = {}
    for line in fm_text.splitlines():
        if ":" in line:
            key, _, val = line.partition(":")
            meta[key.strip()] = val.strip().strip('"').strip("'")
    return meta, body


def read_agent(path: Path) -> dict[str, str]:
    """Read an agent file and return name + description + body."""
    text = path.read_text(encoding="utf-8")
    meta, body = parse_frontmatter(text)
    return {
        "name": meta.get("name", path.stem),
        "description": meta.get("description", ""),
        "body": body,
        "filename": path.name,
    }


def read_rule(path: Path) -> dict[str, str]:
    """Read a rule file and return its title + content."""
    text = path.read_text(encoding="utf-8")
    meta, body = parse_frontmatter(text)

    # Extract first heading as title
    title_match = re.search(r"^#\s+(?:Rule:\s*)?(.+)$", body, re.MULTILINE)
    title = title_match.group(1).strip() if title_match else path.stem

    return {
        "title": title,
        "body": body,
        "filename": path.name,
    }


# Rules that are Claude-specific infrastructure and don't apply to Codex
SKIP_RULES = {
    "agents-vs-skills.md",  # Claude-specific agent/skill distinction
    "break-the-glass.md",  # Claude infrastructure protection
    "ignore-external-agent-files.md",  # Ironic — Codex *needs* AGENTS.md; also skips GEMINI.md
    "lean-claude-md.md",  # Claude-specific
    "public-repo-sync.md",  # Claude infrastructure
    "read-docs-first.md",  # Claude context system
    "skill-outcome-logging.md",  # Claude skill logging
    "severity-gradient.md",  # Claude review agents
    "project-orchestration.md",  # Claude project commands
}

# Rules to include with full body (most important for behaviour)
FULL_RULES = {
    "scope-discipline.md",
    "plan-first.md",
    "data-sensitivity.md",
    "overleaf-separation.md",
    "design-before-results.md",
    "no-hardcoded-results.md",
    "latex-outdir.md",
}

# Agents to skip (Codex-specific ones don't make sense)
SKIP_AGENTS = {
    "codex-research.md",  # Meta — Codex reviewing itself
}


def generate_agents_md(
    agents_dir: Path,
    rules_dir: Path,
) -> str:
    """Generate the full AGENTS.md content."""
    sections: list[str] = []

    # ── Header ───────────────────────────────────────────────────────────
    sections.append(
        """\
# Codex Instructions

> Auto-generated by `sync-to-codex.sh` from Claude Code infrastructure.
> Do not edit manually — changes will be overwritten on next sync.

## Identity

- **User:** the user
- **Role:** PhD Researcher (Year 1)
- **Affiliations:** [University 1], [University 2], [University 3] (research) + [Teaching]
- **Research:** [your research areas]

## Conventions

- **LaTeX:** Build artifacts go to `out/` via `.latexmkrc`. Never leave `.aux`/`.log` in source.
- **Python:** Always use `uv` — never bare `python` or `pip`.
- **R:** Use `<-` for assignment, not `=`.
- **Git:** Many repos are local-only (Dropbox-synced). Check `git remote -v` before pushing.
- **Presentations:** Default to LaTeX Beamer.
- **Data:** `data/raw/` is READ-ONLY. Never modify raw data files.
"""
    )

    # ── Rules ────────────────────────────────────────────────────────────
    rules_section = ["## Rules\n"]

    rule_files = sorted(rules_dir.glob("*.md")) if rules_dir.is_dir() else []
    included = 0
    for rf in rule_files:
        if rf.name in SKIP_RULES:
            continue
        rule = read_rule(rf)
        if rf.name in FULL_RULES:
            rules_section.append(f"### {rule['title']}\n")
            # Strip the top-level heading from body (already used as ###)
            body = re.sub(r"^#\s+.*$", "", rule["body"], count=1, flags=re.MULTILINE).strip()
            # Downshift all headings by 2 levels (## → ####, ### → #####)
            body = re.sub(r"^(#{2,})", lambda m: m.group(1) + "##", body, flags=re.MULTILINE)
            rules_section.append(body)
            rules_section.append("")
        else:
            # Summary only — first paragraph after the heading
            body_lines = rule["body"].splitlines()
            summary_lines: list[str] = []
            past_heading = False
            for line in body_lines:
                if line.startswith("#"):
                    if past_heading:
                        break
                    past_heading = True
                    continue
                if past_heading and line.strip():
                    summary_lines.append(line.strip())
                elif past_heading and not line.strip() and summary_lines:
                    break
            summary = " ".join(summary_lines) if summary_lines else rule["title"]
            rules_section.append(f"- **{rule['title']}:** {summary}")
        included += 1

    sections.append("\n".join(rules_section))

    # ── Agents (as reference) ────────────────────────────────────────────
    agents_section = [
        "\n## Available Review Agents\n",
        "These agents are available in Claude Code for fresh-context review. ",
        "When using Codex, their descriptions inform what each role does.\n",
    ]

    agent_files = sorted(agents_dir.glob("*.md")) if agents_dir.is_dir() else []
    for af in agent_files:
        if af.name in SKIP_AGENTS:
            continue
        agent = read_agent(af)
        # Extract just the first line of description (before examples)
        desc = agent["description"].split("\n")[0] if agent["description"] else ""
        # Clean up escaped newlines from YAML
        desc = desc.replace("\\n", " ").strip()
        agents_section.append(f"- **{agent['name']}:** {desc}")

    sections.append("\n".join(agents_section))

    return "\n".join(sections)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate AGENTS.md for Codex CLI")
    parser.add_argument("--agents-dir", type=Path, required=True)
    parser.add_argument("--rules-dir", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    content = generate_agents_md(args.agents_dir, args.rules_dir)
    args.output.write_text(content, encoding="utf-8")
    print(f"Generated {args.output} ({len(content)} chars, {content.count(chr(10))} lines)")


if __name__ == "__main__":
    main()
