#!/bin/bash
# regen-resource-manifest.sh — snapshot all resource-repo origins to a tracked file
#
# Runs on any machine with a populated resources/ tree (typically the Mini) and
# writes scripts/resource-manifest.txt with one entry per line:
#
#   <category>/<relative-path-from-category>|<origin-url>
#
# The manifest is committed in git, so other machines read it via
# .scripts/ensure-resources.sh to clone whatever's missing.

set -euo pipefail

_CONFIG="$HOME/.config/task-mgmt/path"
[[ ! -f "$_CONFIG" ]] && { echo "Missing $_CONFIG" >&2; exit 1; }
TM="$(head -1 "$_CONFIG" | tr -d '\n')"

BASE="$TM/resources"
MANIFEST="$TM/scripts/resource-manifest.txt"

# Reuse the depth-aware discovery: depth 1..(max_depth+1) from base, looking
# for .git (dir or file — submodules use a file). -prune avoids double counting.
discover() {
    local category_dir="$1"
    local category_name="$2"
    local max_depth="${3:-3}"
    [ ! -d "$category_dir" ] && return
    while IFS= read -r git_path; do
        local repo_dir origin rel
        repo_dir="$(dirname "$git_path")"
        origin="$(git -C "$repo_dir" remote get-url origin 2>/dev/null || true)"
        [ -z "$origin" ] && continue
        rel="${repo_dir#$category_dir/}"
        echo "${category_name}/${rel}|${origin}"
    done < <(find -L "$category_dir" -mindepth 2 -maxdepth "$((max_depth + 1))" -name .git -prune 2>/dev/null)
}

{
    echo "# resource-manifest.txt — auto-generated by .scripts/regen-resource-manifest.sh"
    echo "# Format: <category>/<relative-path>|<origin-url>"
    echo "# Regenerated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo ""
    {
        discover "$BASE/academics"    academics    2
        discover "$BASE/general"      general      2
        discover "$BASE/bibliography" bibliography 2
    } | sort
} > "$MANIFEST"

count=$(grep -c '^[^#]' "$MANIFEST" 2>/dev/null || true)
echo "[manifest] wrote $count entries → $MANIFEST"
